#!/usr/bin/env bash
set -e

if [ -z "$VERSIONS_SH_INCLUDED" ]
then
VERSIONS_SH_INCLUDED=yes

CMAKE_MAJOR_VERSION=3
CMAKE_MINOR_VERSION=4
CMAKE_VERSION=$CMAKE_MAJOR_VERSION.$CMAKE_MINOR_VERSION.3
NINJA_VERSION=1.8.2

BINUTILS_VERSION=2.24
GCC_VERSION=5.1.0
GLIBC_VERSION=2.23
LINUX_MAJOR_VERSION=3
LINUX_VERSION=$LINUX_MAJOR_VERSION.16.2

ZLIB_VERSION=1.2.11
NCURSES_VERSION=6.2
ICU4C_MAJOR_VERSION=61
ICU4C_MINOR_VERSION=1
ICU4C_VERSION=${ICU4C_MAJOR_VERSION}_$ICU4C_MINOR_VERSION
LIBICONV_VERSION=1.15
XZ_VERSION=5.0.5
LIBXML2_VERSION=2.9.2
LIBUUID_VERSION=1.0.3
BASH_VERSION=4.4
COREUTILS_VERSION=8.29
MAKE_VERSION=4.0
SED_VERSION=4.2.2
PYTHON_VERSION=2.7.14
PYTHON2_VERSION=2.7.17
GREP_VERSION=2.20
GAWK_VERSION=4.1.1

GIT_VERSION=2.9.5
CURL_VERSION=7.69.1

SWIFT_VERSION=swift-5.1-RELEASE
fi # End VERSIONS_SH_INCLUDED
