#!/usr/bin/env bash
set -e

GCC_VERSION=4.9.2
BINUTILS_VERSION=2.25
ICU4C_MAJOR_VERSION=63
ICU4C_MINOR_VERSION=1
ICU4C_VERSION=${ICU4C_MAJOR_VERSION}_$ICU4C_MINOR_VERSION
UUID_VERSION=1.0.3
PYTHON_VERSION=2.7.15
SWIFT_VERSION=swift-5.1-RELEASE
ICU_LE_HB_VERSION=1.0.3
