#!/usr/bin/env bash
set -e

GCC_VERSION=4.5.3
BINUTILS_VERSION=2.25
ICU4C_MAJOR_VERSION=63
ICU4C_MINOR_VERSION=1
ICU4C_VERSION=${ICU4C_MAJOR_VERSION}_$ICU4C_MINOR_VERSION
PYTHON_VERSION=2.7.15
SWIFT_VERSION=swift-5.0.2-RELEASE
